import NavbarWithSidebar from "@/components/NavbarWithSidebar"


export const metadata = {
    title: 'Dashboard | Movie Discovery',
    description: 'Generated by create next app',
}

type PropsLayout = {
    children: React.ReactNode
}

const RootLayout = ({ children }: PropsLayout) => {
    return (
        <div>
        <NavbarWithSidebar>
            {children}
        </NavbarWithSidebar>
        </div>

    )
}

export default RootLayout

